
export const projects = [
    {
        id:'1',
        image:'image/blog.png',
        title:'Blog Management Tool',
        tools:["Ejs","Tailwind","Node.js"],
        source:"https://skgblog.onrender.com/",
        description:'This is a Blog Management tool in which you can share your blogs and see others blogs or posts',
        
    },
    {
        id:'2',
        image:'image/game.png',
        title:'Word Scrambling Game',
        tools:["HTML","CSS","JS","Alan-Ai"],
        source:"https://sudhanshukumar321.github.io/guessingGame/",
        description:'As we have mentioned, in word scramble games, one has to re-arrange or unjumble the scrambled letters to make a meaningful word. This game is also known as unscrambling.',
    },
    {
        id:'3',
        image:'image/ticTacToe.png',
        title:'Tic Tac Toe',
        tools:["HTML","CSS","JS","React-js"],
        source:"https://sudhanshukumar321.github.io/tictactoe/",
        description:'Tic-tac-toe is a simple, two-player game that, if played optimally by both players, will always result in a tie. The game is also called noughts and crosses or Xs and Os.',
    },
    {
        id:'4',
        image:'image/calculator.png',
        title:'Calculator',
        tools:["HTML","CSS","JS"],
        source:"#",
        description:'This is a simple Calculator in which you can do almost all basic operations such addition, subtraction, multiplication, division etc.',
    },
    {
        id:'5',
        image:'image/ecommerce.png',
        title:'E-Commerce',
        tools:[ "HTML","CSS","JS" ],
        source:"#",
        description:'Ecommerce stands for “electronic commerce.” Ecommerce websites are built to connect shoppers to products or services for trading online. On the most basic level, they provide everything we need for online shopping.',
    },
    {
        id:'6',
        image:'image/portfolio.png',
        title:'Portfolio 2',
        tools:["react","Tailwind"],
        source:"https://sudhanshu-kumar-2.netlify.app/",
        description:'This is my 2nd portfolio design page',
    },
    {
        id:'7',
        image:'image/recipe.png',
        title:'Food recipes page',
        tools:["Html","CSS","Js"],
        source:"https://sudhanshu-recipe.netlify.app/",
        description:'NA',
    },
    { 
        id:'8',
        image:'image/translator.png',
        title:'Translator',
        tools:["Html","CSS","Js"],
        source:"#",
        description:'NA',
    },
];